name:                hashbench
license:             BSD3

dependencies:
- base >= 4.7 && < 5
- ghc-prim
- text

library:
  source-dirs: src
  c-sources: cbits/fnv.c
  ghc-options: -O2

tests:
  hashbench-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - hashbench
    - hspec

benchmarks:
  hashbench:
    main:                Main.hs
    source-dirs:         bench
    dependencies:
    - hashbench
    - gauge
